// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzcphkjtdniotqypmabw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6Y3Boa2p0ZG5pb3RxeXBtYWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NTcxNzIsImV4cCI6MjA3NTEzMzE3Mn0.GPGYNaPPN-l_4tXw0JyrmOQWE8p0hXUIipQfGhzW19E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});